-- ============================================================
-- PREPNEST / Ji Sushi — idempotent schema (safe to re-run)
-- ============================================================

-- Menu items with "Item 86" toggle
CREATE TABLE IF NOT EXISTS menu_items (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  price NUMERIC(10,2) NOT NULL,
  category TEXT,
  image_url TEXT,
  is_available BOOLEAN DEFAULT TRUE
);

-- Backfill: add image_url to pre-existing databases (no-op if already present)
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS image_url TEXT;

-- Orders (dine-in vs takeaway)
CREATE TABLE IF NOT EXISTS orders (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  order_no INT GENERATED BY DEFAULT AS IDENTITY,
  customer_name TEXT,
  customer_phone TEXT,
  table_number INT,
  items JSONB NOT NULL,
  status TEXT DEFAULT 'pending',
  total_price NUMERIC(10,2),
  created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS pickup_minutes INT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;

-- ============================================================
-- Takeaway reliability + lifecycle
--
-- A customer ordering from mobile data 15 minutes away is the normal case, not
-- the edge case. The columns below exist so that a dropped connection cannot
-- create a duplicate order, and so the customer can confirm the kitchen has
-- actually seen theirs without phoning to ask.
-- ============================================================

-- Dedupe key generated by the client, one per checkout attempt. If the response
-- is lost and the customer taps again, the retry carries the SAME key and the
-- unique index turns the second insert into a no-op instead of a second dinner.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS idempotency_key TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS orders_idempotency_idx
  ON orders(idempotency_key) WHERE idempotency_key IS NOT NULL;

-- Unguessable handle for the customer's own status page. Not the order number:
-- order numbers are sequential, so /ordre/41 would let anyone read /ordre/42.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS public_token TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS orders_public_token_idx
  ON orders(public_token) WHERE public_token IS NOT NULL;

-- Lifecycle timestamps. Each state change is recorded rather than overwritten,
-- so "how long did we take last Friday" is answerable later.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS accepted_at    TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ready_at       TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancelled_at   TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancel_reason  TEXT;
-- What the kitchen promised the customer, as a real time rather than "30 min".
ALTER TABLE orders ADD COLUMN IF NOT EXISTS ready_estimate TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS channel        TEXT DEFAULT 'takeaway';

-- Valid states. Applied only if every existing row already conforms, so
-- re-running this on a live database cannot fail halfway through.
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'orders_status_valid')
     AND NOT EXISTS (
       SELECT 1 FROM orders
       WHERE status NOT IN ('pending','accepted','ready','completed','cancelled')
     )
  THEN
    ALTER TABLE orders ADD CONSTRAINT orders_status_valid
      CHECK (status IN ('pending','accepted','ready','completed','cancelled'));
  END IF;
END $$;

-- History is searched by phone and by order number, both on recent rows only.
CREATE INDEX IF NOT EXISTS orders_phone_idx  ON orders(customer_phone);
CREATE INDEX IF NOT EXISTS orders_no_idx     ON orders(order_no DESC);

-- ============================================================
-- Menu ordering
--
-- `menu_items.id` is a random UUID, so `ORDER BY id` produced an ARBITRARY
-- sequence: the takeaway menu listed "50 Box, 10 Box, 90 Box…" while the paper
-- menu on the counter read 10, 20, 30. Nothing errored; it just looked wrong
-- to every customer.
--
-- sort_order is backfilled from the seed order below, which is the paper menu's
-- own sequence. Category order is then derived from MIN(sort_order), so a
-- category cannot drift out of place either.
-- ============================================================
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS sort_order INT;

WITH ordered AS (
  SELECT name, ROW_NUMBER() OVER () AS rn
  FROM (VALUES
  ('Edamame bønner'),
  ('Edamame bønner med chili'),
  ('Tangsalat'),
  ('Kimchi'),
  ('Wasabi bønner'),
  ('Rejechips'),
  ('Søde kartofler'),
  ('Sushi ris'),
  ('Vegetar forårsruller (5 stk.)'),
  ('Gyoza (5 stk.)'),
  ('Ebi fry (5 stk.)'),
  ('Kyllingefilet'),
  ('Oksekød'),
  ('Lam'),
  ('Kæmpe tigerreje'),
  ('Laks (spyd)'),
  ('Kylling kødboller'),
  ('Asparges med bacon'),
  ('Squash'),
  ('Laks Sashimi (6 skiver)'),
  ('Tun Sashimi (6 skiver)'),
  ('Sashimi Menu (12 skiver og 5 tigerrejer)'),
  ('Tempura Rejer Tun Deluxe Roll (8 stk.)'),
  ('Tempura Rejer Grillet Laks Deluxe Roll (8 stk.)'),
  ('Tempura Rejer Avocado Deluxe Roll (8 stk.)'),
  ('Tempura Rejer Rainbow Deluxe Roll (8 stk.)'),
  ('Tempura Kylling Deluxe Roll (8 stk.)'),
  ('Vegetar Deluxe Roll (8 stk.)'),
  ('Grillet Laks Deluxe Roll (8 stk.)'),
  ('Laks Deluxe Roll (8 stk.)'),
  ('Laks Avocado Deluxe Roll (8 stk.)'),
  ('Rainbow Roll (8 stk.)'),
  ('Tun Avocado Deluxe Roll (8 stk.)'),
  ('Tempura Surimi Deluxe Roll (8 stk.)'),
  ('Sesamfrø Ebi Tempura (8 stk.)'),
  ('San Francisco (8 stk.)'),
  ('Super California (8 stk.)'),
  ('Alaska (8 stk.)'),
  ('California (8 stk.)'),
  ('Spicy Laks (8 stk.)'),
  ('Spicy Rejer (8 stk.)'),
  ('Spicy Tun (8 stk.)'),
  ('Tigerrejer (8 stk.)'),
  ('Tun (8 stk.)'),
  ('Laks (8 stk.)'),
  ('Agurk (8 stk.)'),
  ('Avocado (8 stk.)'),
  ('Tun med avocado (8 stk.)'),
  ('Laks med avocado (8 stk.)'),
  ('Yami Ebi Rejer (5 stk.)'),
  ('Tempura Rejer (5 stk.)'),
  ('Spicy Rejer (5 stk.)'),
  ('Big Alaska (5 stk.)'),
  ('California Laks (5 stk.)'),
  ('Spicy Laks (5 stk.)'),
  ('Spicy Tun (5 stk.)'),
  ('California (5 stk.)'),
  ('Vegetar (5 stk.)'),
  ('Laks'),
  ('Grillet Laks'),
  ('Laks med Avocado'),
  ('Grillet Laks med Bønnespirer'),
  ('Tun'),
  ('Tun Tataki'),
  ('Tun med Avocado'),
  ('Tun med Forårsløg'),
  ('Hvidfisk'),
  ('Tigerrejer'),
  ('Tigerrejer med Spicy Sauce'),
  ('Krebsehaler'),
  ('Laks Gunkan'),
  ('Ørredrogn'),
  ('Avocado'),
  ('Agurk'),
  ('Inari Tofu'),
  ('Rispapir Laks (8 stk.)'),
  ('Rispapir Ebi Rejer (8 stk.)'),
  ('Rispapir Tempura Kylling (8 stk.)'),
  ('Rispapir Oksekød (8 stk.)'),
  ('Goma dressing'),
  ('Hjemmelavet wasabi-mayo'),
  ('Hjemmelavet chili-mayo'),
  ('Hjemmelavet teriyaki'),
  ('Sød chilisauce'),
  ('Ebi Tempura Menu (24 stk.)'),
  ('Nigiri Menu (8 stk.)'),
  ('Uramaki Menu (32 stk.)'),
  ('Vegetar Menu (18 stk.)'),
  ('10 Box (10 stk.)'),
  ('20 Box (20 stk.)'),
  ('30 Box (30 stk.)'),
  ('40 Box (40 stk.)'),
  ('50 Box (50 stk.)'),
  ('60 Box (60 stk.)'),
  ('70 Box (70 stk.)'),
  ('80 Box (80 stk.)'),
  ('Box 90 (90 stk.)'),
  ('Box 100 (100 stk.)'),
  ('Super Tilbud Menu 1 (36 stk.)'),
  ('Super Tilbud Menu 2 (70 stk.)'),
  ('Super Tilbud Menu 3 (104 stk.)')
  ) AS t(name)
)
UPDATE menu_items m
   SET sort_order = o.rn
  FROM ordered o
 WHERE m.name = o.name
   AND (m.sort_order IS DISTINCT FROM o.rn);

-- Anything added later without an explicit position lands at the end,
-- alphabetically, rather than randomly.
UPDATE menu_items SET sort_order = 9000 WHERE sort_order IS NULL;
CREATE INDEX IF NOT EXISTS menu_items_sort_idx ON menu_items(sort_order);

-- ============================================================
-- Allergens — EU Reg. 1169/2011 Annex II
--
-- For food sold at a distance, allergen information must reach the customer
-- BEFORE they buy. A takeaway website is distance selling.
--
-- `allergens_reviewed` defaults to FALSE deliberately. Until someone in the
-- kitchen confirms a dish, the site shows "spørg os" rather than a list: an
-- unchecked dish and a dish with no allergens must not look the same to a
-- person with an allergy. See lib/allergens.ts and tests/allergens.test.ts.
-- ============================================================
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS allergens TEXT[] DEFAULT '{}';
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS allergens_reviewed BOOLEAN DEFAULT FALSE;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS allergen_note TEXT;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS allergens_reviewed_at TIMESTAMPTZ;

-- Only the 14 declarable allergens may be stored. A typo would otherwise be
-- dropped at display time and read as "cleared".
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'menu_items_allergens_valid') THEN
    ALTER TABLE menu_items ADD CONSTRAINT menu_items_allergens_valid CHECK (
      allergens <@ ARRAY['gluten','krebsdyr','aeg','fisk','jordnoedder','soja','maelk',
                         'noedder','selleri','sennep','sesam','sulfitter','lupin','bloeddyr']::TEXT[]
    );
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS menu_items_allergens_idx ON menu_items USING GIN (allergens);

-- How far the declaration can be trusted:
--   confirmed — a human in the kitchen checked this dish
--   standard  — derived from the dish type (sashimi is fish, tempura is wheat
--               batter). Shown to customers with "standardopskrift" attached.
--   uncertain — not knowable from the menu. Shows "ring til os" and nothing else.
--
-- The middle tier exists because marking all 101 dishes "ask us" is technically
-- safe and practically useless: a warning on everything stops being read.
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS allergen_confidence TEXT DEFAULT 'uncertain';

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'menu_items_allergen_confidence_valid') THEN
    ALTER TABLE menu_items ADD CONSTRAINT menu_items_allergen_confidence_valid
      CHECK (allergen_confidence IN ('confirmed','standard','uncertain'));
  END IF;
END $$;

-- ============================================================
-- Searchable phone number
--
-- Customers type "31 33 44 86", "+45 31334486", "3133 4486". Stored verbatim,
-- none of those match a search for "31334486" — so the 30-day history lookup by
-- phone silently returned nothing for most customers. A generated column
-- normalises once, at write time, and cannot drift from the raw value.
-- ============================================================
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
     WHERE table_name = 'orders' AND column_name = 'phone_digits'
  ) THEN
    ALTER TABLE orders ADD COLUMN phone_digits TEXT
      GENERATED ALWAYS AS (regexp_replace(COALESCE(customer_phone, ''), '[^0-9]', '', 'g')) STORED;
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS orders_phone_digits_idx ON orders(phone_digits);


-- ============================================================
-- Retention: 30 days
--
-- Two reasons, pointing the same way. The kitchen needs to look up a disputed
-- order from last week; nobody needs one from last year. And these rows are
-- names and phone numbers — under GDPR, keeping them longer than the purpose
-- requires is the violation, so a fixed window is the compliant answer as well
-- as the useful one.
-- ============================================================
-- ============================================================
-- System events — self-contained monitoring
--
-- Without this, a checkout failing at 19:00 on a Friday is invisible until a
-- customer phones to ask where their food is. A restaurant should not need a
-- second SaaS account to learn its own ordering page is broken.
--
-- Events, not logs: one row per thing worth a human knowing about. Surfaced at
-- /kitchen/selftest and purged on the same 30-day cycle as orders.
-- ============================================================
CREATE TABLE IF NOT EXISTS system_events (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  severity    TEXT NOT NULL DEFAULT 'error',
  source      TEXT NOT NULL,
  message     TEXT NOT NULL,
  detail      JSONB,
  CONSTRAINT system_events_severity_valid CHECK (severity IN ('info','warn','error'))
);

CREATE INDEX IF NOT EXISTS system_events_recent_idx   ON system_events(created_at DESC);
CREATE INDEX IF NOT EXISTS system_events_severity_idx ON system_events(severity, created_at DESC);

-- Error messages can carry fragments of a request, so staff-only by construction.
ALTER TABLE system_events ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- Outbound message queue
--
-- Everything the system needs to tell a human goes here first: a customer's
-- "din mad er klar", an owner alert that checkout is failing. Nothing sends
-- directly, because the Android phone acting as SMS gateway is not always
-- reachable — it sleeps, loses signal, gets left in a coat. A queue waits; a
-- direct send is simply lost.
-- ============================================================
CREATE TABLE IF NOT EXISTS outbound_messages (
  id           UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at   TIMESTAMPTZ DEFAULT NOW(),
  channel      TEXT NOT NULL DEFAULT 'sms',
  recipient    TEXT NOT NULL,
  body         TEXT NOT NULL,
  status       TEXT NOT NULL DEFAULT 'pending',
  attempts     INT  NOT NULL DEFAULT 0,
  last_error   TEXT,
  sent_at      TIMESTAMPTZ,
  claimed_at   TIMESTAMPTZ,
  -- Ties a message to what caused it, so one status change cannot be texted
  -- twice if the gateway retries or two tabs both advance an order.
  dedupe_key   TEXT,
  priority     INT NOT NULL DEFAULT 5,
  order_id     UUID REFERENCES orders(id) ON DELETE SET NULL,
  CONSTRAINT outbound_status_valid CHECK (status IN ('pending','claimed','sent','failed','skipped')),
  CONSTRAINT outbound_channel_valid CHECK (channel IN ('sms','webhook','email'))
);

CREATE UNIQUE INDEX IF NOT EXISTS outbound_dedupe_idx
  ON outbound_messages(dedupe_key) WHERE dedupe_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS outbound_pending_idx
  ON outbound_messages(status, priority, created_at) WHERE status IN ('pending','claimed');

-- ── SMS: dormant now, live later ──
--
-- The site can launch with no gateway. While sms_enabled is false, messages are
-- RECORDED as skipped rather than queued — so connecting a phone weeks later
-- cannot flush a backlog of "din ordre er klar" for meals eaten in September.
-- One such text teaches a customer to ignore every message you ever send.
--
-- expires_at is the second line of defence: every message carries its own shelf
-- life, so nothing stale goes out even if the flag were wrong.
-- Manual pause. Opening hours cover the predictable case; this covers a rush
-- the kitchen cannot see the end of, a dead fryer, an illness. Without it the
-- only way to stop orders is to take the site down — which also hides the
-- address, the phone number and the menu.
ALTER TABLE settings ADD COLUMN IF NOT EXISTS ordering_paused BOOLEAN DEFAULT FALSE;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS pause_message TEXT;

-- Login attempts. The previous limiter was in-memory, which on serverless means
-- per instance: "5 per 10 minutes" was really 5 per instance across many. Not a
-- defence against a 4-digit PIN. Shared state gives one counter.
CREATE TABLE IF NOT EXISTS auth_attempts (
  id         BIGSERIAL PRIMARY KEY,
  at         TIMESTAMPTZ DEFAULT NOW(),
  ip         TEXT,
  ok         BOOLEAN NOT NULL,
  user_agent TEXT
);
CREATE INDEX IF NOT EXISTS auth_attempts_recent_idx ON auth_attempts(at DESC);
CREATE INDEX IF NOT EXISTS auth_attempts_ip_idx     ON auth_attempts(ip, at DESC);
ALTER TABLE auth_attempts ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION recent_auth_failures(p_ip TEXT, p_minutes INT DEFAULT 15)
RETURNS TABLE (ip_failures BIGINT, global_failures BIGINT)
LANGUAGE sql SECURITY INVOKER SET search_path = public, pg_catalog AS $$
  SELECT COUNT(*) FILTER (WHERE ip = p_ip AND NOT ok),
         COUNT(*) FILTER (WHERE NOT ok)
    FROM auth_attempts
   WHERE at > NOW() - (p_minutes || ' minutes')::INTERVAL;
$$;
REVOKE EXECUTE ON FUNCTION public.recent_auth_failures(TEXT, INT) FROM anon, authenticated, public;

ALTER TABLE settings ADD COLUMN IF NOT EXISTS sms_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS sms_gateway_last_seen TIMESTAMPTZ;

ALTER TABLE outbound_messages ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
ALTER TABLE outbound_messages ADD COLUMN IF NOT EXISTS skip_reason TEXT;
CREATE INDEX IF NOT EXISTS outbound_expiry_idx
  ON outbound_messages(expires_at) WHERE status = 'pending';

INSERT INTO settings (id) VALUES ('main') ON CONFLICT (id) DO NOTHING;

ALTER TABLE outbound_messages ENABLE ROW LEVEL SECURITY;

-- A message stuck in 'claimed' means the phone took it and never reported back.
-- Release it so the next poll picks it up; give up after five attempts rather
-- than retrying into the void.
CREATE OR REPLACE FUNCTION release_stale_claims(older_than_minutes INT DEFAULT 5)
RETURNS INT LANGUAGE plpgsql SECURITY INVOKER SET search_path = public, pg_catalog AS $$
DECLARE released INT;
BEGIN
  UPDATE outbound_messages SET status = 'pending', claimed_at = NULL
   WHERE status = 'claimed'
     AND claimed_at < NOW() - (older_than_minutes || ' minutes')::INTERVAL
     AND attempts < 5;
  GET DIAGNOSTICS released = ROW_COUNT;
  UPDATE outbound_messages SET status = 'failed' WHERE status = 'claimed' AND attempts >= 5;
  RETURN released;
END $$;

CREATE OR REPLACE FUNCTION purge_old_events(retain_days INT DEFAULT 30)
RETURNS INT LANGUAGE plpgsql SECURITY INVOKER SET search_path = public, pg_catalog AS $$
DECLARE removed INT;
BEGIN
  DELETE FROM system_events WHERE created_at < NOW() - (retain_days || ' days')::INTERVAL;
  GET DIAGNOSTICS removed = ROW_COUNT;
  RETURN removed;
END $$;

CREATE OR REPLACE FUNCTION purge_old_orders(retain_days INT DEFAULT 30)
RETURNS INT LANGUAGE plpgsql AS $$
DECLARE removed INT;
BEGIN
  DELETE FROM orders WHERE created_at < NOW() - (retain_days || ' days')::INTERVAL;
  GET DIAGNOSTICS removed = ROW_COUNT;
  RETURN removed;
END $$;

CREATE INDEX IF NOT EXISTS orders_status_idx ON orders(status);
CREATE INDEX IF NOT EXISTS orders_created_idx ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS menu_items_category_idx ON menu_items(category);

-- Loyalty program (phone = primary key)
CREATE TABLE IF NOT EXISTS loyalty_customers (
  phone TEXT PRIMARY KEY,
  name TEXT,
  stamps INT DEFAULT 0
);

-- Site theme / design settings (single row, JSONB). Managed from admin "Design" tab.
CREATE TABLE IF NOT EXISTS settings (
  id TEXT PRIMARY KEY,
  theme JSONB NOT NULL DEFAULT '{}'::jsonb
);
INSERT INTO settings (id, theme) VALUES ('main', '{}')
ON CONFLICT (id) DO NOTHING;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS webhook_url TEXT;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS webhook_secret TEXT;

-- Enable Realtime for instant KDS + menu updates
-- `orders` is deliberately NOT in the realtime publication.
--
-- Realtime respects RLS, and anon has no policy on orders — but publishing a
-- table of phone numbers is a door worth not building at all. The kitchen
-- screen polls an authenticated route instead.
--
-- The DROP matters: an earlier version of this schema ADDed orders to the
-- publication, and re-running the file on an existing database would otherwise
-- leave that in place. Removing it is the whole point of re-running.
DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime DROP TABLE orders;
EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE menu_items;
EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- ============================================================
-- RLS — least privilege
--
-- The anon key is PUBLIC. It ships inside the JavaScript bundle of every page,
-- so `USING (true)` is not a permission model: it means anyone who opens
-- devtools can read every customer's name and phone number, rewrite prices, or
-- delete tonight's orders — without ever loading the app's UI.
--
-- Rule applied below: anon may read the menu, and nothing else. Every write,
-- and every read of personal data, goes through a server route holding the
-- service-role key, which bypasses RLS by design.
-- ============================================================

ALTER TABLE menu_items        ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders            ENABLE ROW LEVEL SECURITY;
ALTER TABLE loyalty_customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings          ENABLE ROW LEVEL SECURITY;   -- was never enabled; holds webhook_secret

-- Remove the old permissive policies wherever they were applied.
DROP POLICY IF EXISTS anon_all ON menu_items;
DROP POLICY IF EXISTS anon_all ON orders;
DROP POLICY IF EXISTS anon_all ON loyalty_customers;
DROP POLICY IF EXISTS anon_all ON settings;

-- menu_items: public read. It is the menu — it is on the wall outside.
-- No public write: a writable price column is a 1 kr sushi box.
DROP POLICY IF EXISTS menu_public_read ON menu_items;
CREATE POLICY menu_public_read ON menu_items
  FOR SELECT TO anon, authenticated
  USING (true);

-- orders: no anon access at all, in either direction.
--   reads  -> /api/kitchen/orders (staff session + service role)
--   writes -> /api/checkout       (server-side repricing + service role)
-- No policy is created, so with RLS on, anon is denied by default.

-- loyalty_customers: personal data. Server-side only, same reasoning.

-- settings: holds webhook_secret. Server-side only. Never expose to a browser.

-- push_subscriptions: delivery endpoints are write-once from the client and
-- must not be enumerable — otherwise anyone can list, or hijack, staff alerts.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'push_subscriptions') THEN
    EXECUTE 'ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY';
    EXECUTE 'DROP POLICY IF EXISTS anon_all_push_subscriptions ON push_subscriptions';
  END IF;
END $$;

-- ============================================================
-- Full Ji Sushi menu (98 items) — re-running will NOT duplicate
-- ============================================================
INSERT INTO menu_items (name, description, price, category) VALUES
('Edamame bønner', NULL, 45, 'Forretter'),
('Edamame bønner med chili', NULL, 50, 'Forretter'),
('Tangsalat', NULL, 55, 'Forretter'),
('Kimchi', NULL, 55, 'Forretter'),
('Wasabi bønner', NULL, 45, 'Forretter'),
('Rejechips', NULL, 39, 'Forretter'),
('Søde kartofler', NULL, 35, 'Forretter'),
('Sushi ris', NULL, 28, 'Forretter'),
('Vegetar forårsruller (5 stk.)', NULL, 40, 'Forretter'),
('Gyoza (5 stk.)', 'Grøntsager og svinekød', 50, 'Forretter'),
('Ebi fry (5 stk.)', NULL, 70, 'Forretter'),
('Kyllingefilet', NULL, 33, 'Sticks'),
('Oksekød', NULL, 38, 'Sticks'),
('Lam', NULL, 38, 'Sticks'),
('Kæmpe tigerreje', NULL, 35, 'Sticks'),
('Laks (spyd)', NULL, 35, 'Sticks'),
('Kylling kødboller', NULL, 30, 'Sticks'),
('Asparges med bacon', NULL, 35, 'Sticks'),
('Squash', NULL, 25, 'Sticks'),
('Laks Sashimi (6 skiver)', 'Serveres med ris', 85, 'Sashimi'),
('Tun Sashimi (6 skiver)', 'Serveres med ris', 89, 'Sashimi'),
('Sashimi Menu (12 skiver og 5 tigerrejer)', 'Serveres med ris', 205, 'Sashimi'),
('Tempura Rejer Tun Deluxe Roll (8 stk.)', 'Tempura rejer, avocado og agurk, toppet med tun og spicy mayo', 125, 'Toppet maki'),
('Tempura Rejer Grillet Laks Deluxe Roll (8 stk.)', 'Tempura rejer, avocado og mango, toppet med grillet laks og spicy mayo', 125, 'Toppet maki'),
('Tempura Rejer Avocado Deluxe Roll (8 stk.)', 'Tempura rejer, avocado og agurk, toppet med avocado og teriyaki', 125, 'Toppet maki'),
('Tempura Rejer Rainbow Deluxe Roll (8 stk.)', 'Tempura rejer, avocado og agurk, toppet med laks, tun, rejer, hvidfisk og bønnespirer', 125, 'Toppet maki'),
('Tempura Kylling Deluxe Roll (8 stk.)', 'Tempura kylling og agurk, toppet med avocado og spicy mayo', 120, 'Toppet maki'),
('Vegetar Deluxe Roll (8 stk.)', 'Salat mix, tofu, agurk og avocado, toppet med tangsalat og chili sesamfrø', 115, 'Toppet maki'),
('Grillet Laks Deluxe Roll (8 stk.)', 'Laks, avocado og agurk, toppet med grillet laks og forårsløg', 125, 'Toppet maki'),
('Laks Deluxe Roll (8 stk.)', 'Laks, avocado og agurk, toppet med laks og forårsløg', 125, 'Toppet maki'),
('Laks Avocado Deluxe Roll (8 stk.)', 'Laksemousse og tobiko, toppet med forårsløg og avocado', 120, 'Toppet maki'),
('Rainbow Roll (8 stk.)', 'Surimi, avocado og agurk, toppet med laks, rejer og hvidfisk', 120, 'Toppet maki'),
('Tun Avocado Deluxe Roll (8 stk.)', 'Tun og tobiko, toppet med tun og forårsløg', 120, 'Toppet maki'),
('Tempura Surimi Deluxe Roll (8 stk.)', 'Tempura surimi, avocado og agurk, toppet med bønnespirer', 120, 'Toppet maki'),
('Sesamfrø Ebi Tempura (8 stk.)', 'Ebi rejer, avocado, agurk og spicy sauce', 93, 'Uramaki'),
('San Francisco (8 stk.)', 'Laks, avocado, agurk, basilikum og ørredrogn', 90, 'Uramaki'),
('Super California (8 stk.)', 'Krebsehaler, avocado, agurk og tobiko', 90, 'Uramaki'),
('Alaska (8 stk.)', 'Laks, flødeost, avocado, agurk og tobiko', 90, 'Uramaki'),
('California (8 stk.)', 'Surimi, avocado, agurk og sesamfrø', 80, 'Uramaki'),
('Spicy Laks (8 stk.)', 'Laks, spicy sauce, agurk, avocado og sesamfrø', 83, 'Uramaki'),
('Spicy Rejer (8 stk.)', 'Tigerrejer, spicy sauce, agurk, avocado og sesamfrø', 85, 'Uramaki'),
('Spicy Tun (8 stk.)', 'Tun, spicy sauce, agurk, avocado og sesamfrø', 85, 'Uramaki'),
('Tigerrejer (8 stk.)', NULL, 53, 'Hosomaki'),
('Tun (8 stk.)', NULL, 50, 'Hosomaki'),
('Laks (8 stk.)', NULL, 50, 'Hosomaki'),
('Agurk (8 stk.)', NULL, 43, 'Hosomaki'),
('Avocado (8 stk.)', NULL, 43, 'Hosomaki'),
('Tun med avocado (8 stk.)', NULL, 53, 'Hosomaki'),
('Laks med avocado (8 stk.)', NULL, 53, 'Hosomaki'),
('Yami Ebi Rejer (5 stk.)', 'Ebi rejer, avocado og mango', 73, 'Futomaki'),
('Tempura Rejer (5 stk.)', 'Ebi rejer, avocado og agurk', 70, 'Futomaki'),
('Spicy Rejer (5 stk.)', 'Tigerrejer, avocado og agurk', 70, 'Futomaki'),
('Big Alaska (5 stk.)', 'Laks, flødeost, agurk, avocado og tobiko', 70, 'Futomaki'),
('California Laks (5 stk.)', 'Surimi, laks, avocado og agurk', 73, 'Futomaki'),
('Spicy Laks (5 stk.)', 'Laks, avocado og agurk', 70, 'Futomaki'),
('Spicy Tun (5 stk.)', 'Tun, agurk og avocado', 73, 'Futomaki'),
('California (5 stk.)', 'Surimi, avocado og agurk', 65, 'Futomaki'),
('Vegetar (5 stk.)', 'Avocado, agurk, tofu og salat mix', 60, 'Futomaki'),
('Laks', NULL, 22, 'Nigiri'),
('Grillet Laks', NULL, 24, 'Nigiri'),
('Laks med Avocado', NULL, 24, 'Nigiri'),
('Grillet Laks med Bønnespirer', NULL, 24, 'Nigiri'),
('Tun', NULL, 22, 'Nigiri'),
('Tun Tataki', NULL, 24, 'Nigiri'),
('Tun med Avocado', NULL, 24, 'Nigiri'),
('Tun med Forårsløg', NULL, 24, 'Nigiri'),
('Hvidfisk', NULL, 24, 'Nigiri'),
('Tigerrejer', NULL, 22, 'Nigiri'),
('Tigerrejer med Spicy Sauce', NULL, 24, 'Nigiri'),
('Krebsehaler', NULL, 27, 'Nigiri'),
('Laks Gunkan', NULL, 27, 'Nigiri'),
('Ørredrogn', NULL, 27, 'Nigiri'),
('Avocado', NULL, 20, 'Nigiri'),
('Agurk', NULL, 17, 'Nigiri'),
('Inari Tofu', NULL, 22, 'Nigiri'),
('Rispapir Laks (8 stk.)', 'Laks, salat mix, agurk og avocado med spicy sauce', 85, 'Rispapir ruller'),
('Rispapir Ebi Rejer (8 stk.)', 'Ebi rejer, salat mix, agurk og avocado med spicy sauce og teriyaki sauce', 85, 'Rispapir ruller'),
('Rispapir Tempura Kylling (8 stk.)', 'Tempura kylling, salat mix, agurk og avocado med spicy sauce og goma sauce', 85, 'Rispapir ruller'),
('Rispapir Oksekød (8 stk.)', 'Oksekød, salat mix, agurk og avocado med teriyaki sauce', 85, 'Rispapir ruller'),
('Goma dressing', NULL, 10, 'Tilbehør'),
('Hjemmelavet wasabi-mayo', NULL, 10, 'Tilbehør'),
('Hjemmelavet chili-mayo', NULL, 10, 'Tilbehør'),
('Hjemmelavet teriyaki', NULL, 10, 'Tilbehør'),
('Sød chilisauce', NULL, 10, 'Tilbehør'),
('Ebi Tempura Menu (24 stk.)', '8 deluxe ebi tempura rejer med avocado, 8 deluxe ebi tempura rejer med laks, 8 deluxe ebi tempura rejer med regnbue', 328, 'Menuer'),
('Nigiri Menu (8 stk.)', '2 laks, 2 laks med avocado, 2 grillet laks, 2 tun', 138, 'Menuer'),
('Uramaki Menu (32 stk.)', '8 ebi tempura rejer med sesamfrø, 8 laks deluxe roll, 8 rainbow roll, 8 Alaska roll', 388, 'Menuer'),
('Vegetar Menu (18 stk.)', '8 toppet maki: Vegetar Roll med avocado, 8 hosomaki: agurk, 2 nigiri: 1 tofu, 1 agurk', 168, 'Menuer'),
('10 Box (10 stk.)', '8 uramaki: ebi tempura rejer med sesamfrø, 2 nigiri: laks', 120, 'Sushi Box'),
('20 Box (20 stk.)', '8 uramaki: ebi tempura rejer med sesamfrø, 8 uramaki: spicy laks, 4 nigiri: 2 laks, 2 tun', 260, 'Sushi Box'),
('30 Box (30 stk.)', '8 uramaki: ebi tempura rejer med sesamfrø, 8 uramaki: spicy laks, 8 toppet maki: rainbow roll, 6 nigiri: 2 laks, 2 tun, 2 rejer', 360, 'Sushi Box'),
('40 Box (40 stk.)', '8 uramaki: California, 8 uramaki: Spicy laks, 8 toppet maki: ebi tempura rejer med avocado, 16 nigiri: 4 laks, 4 tun, 4 rejer, 4 grillet laks', 460, 'Sushi Box'),
('50 Box (50 stk.)', '8 uramaki: Spicy laks, 8 uramaki: California, 8 toppet maki: Ebi tempura rejer med avocado, 8 toppet maki: Laks deluxe roll, 18 nigiri: 4 laks, 4 tun, 4 rejer, 4 grillet laks, 2 avocado', 600, 'Sushi Box'),
('60 Box (60 stk.)', '8 uramaki: Spicy tun, 8 uramaki: Alaska, 8 toppet maki: Ebi tempura rejer med avocado, 8 toppet maki: Laks deluxe roll, 8 Rainbow roll, 20 nigiri: 5 laks, 5 tun, 5 rejer, 5 grillet laks', 700, 'Sushi Box'),
('70 Box (70 stk.)', '8 uramaki: Spicy tun, 8 uramaki: Alaska, 8 toppet maki: Ebi tempura med avocado, 8 toppet maki: Ebi tempura med laks, 8 toppet maki: Rainbow roll, 8 toppet maki: Laks deluxe roll, 22 nigiri: 5 laks, 5 tun, 5 rejer, 5 grillet laks, 2 krebsehaler', 820, 'Sushi Box'),
('80 Box (80 stk.)', '8 uramaki: Spicy tun, 8 uramaki: Alaska, 8 uramaki: California, 8 toppet maki: Ebi tempura med avocado, 8 toppet maki: Ebi tempura med laks, 8 toppet maki: Rainbow roll, 8 toppet maki: Laks deluxe roll, 24 nigiri: 5 laks, 5 tun, 5 rejer, 5 grillet laks, 4 krebsehaler', 950, 'Sushi Box'),
('Box 90 (90 stk.)', 'Sammensættes af sushikok', 1050, 'Sushi Box'),
('Box 100 (100 stk.)', 'Sammensættes af sushikok', 1200, 'Sushi Box'),
-- Super Tilbud: the 3 fixed takeaway combos, priced to match the site promo exactly
('Super Tilbud Menu 1 (36 stk.)', '8 nigiri (2 stk. af hver: rejer, laks, tun og flamberet laks), 6 futomaki med tempura rejer, 6 futomaki med tempura kylling, 8 Alaska med laks, 8 topping med tempurareje og flamberet laks', 300, 'Super Tilbud'),
('Super Tilbud Menu 2 (70 stk.)', '12 nigiri (3 stk. af hver: rejer, laks, tun og flamberet laks), 12 futomaki med tempura rejer, 6 futomaki med tempura kylling, 8 Alaska med laks, 8 spicy rejer, 8 topping med tempurareje og flamberet laks, 8 topping rainbow med surimi, 8 hosomaki med agurk', 530, 'Super Tilbud'),
('Super Tilbud Menu 3 (104 stk.)', '16 nigiri (4 stk. af hver: rejer, laks, tun og flamberet laks), 12 futomaki med tempura rejer, 12 futomaki med tempura kylling, 8 Alaska med laks, 8 flying chicken, 8 spicy rejer, 8 spicy tun, 8 topping med tempurareje og flamberet laks, 8 topping rainbow med surimi, 8 hosomaki med agurk, 8 hosomaki med laks', 750, 'Super Tilbud')
ON CONFLICT (name) DO NOTHING;
-- ---- Web Push subscriptions (kitchen iPad alerts) ----
CREATE TABLE IF NOT EXISTS push_subscriptions (
  endpoint TEXT PRIMARY KEY,
  keys JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Locked down: no anon policy. Subscriptions are registered through a server
-- route, and read only by the alert sender using the service-role key.
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS anon_all_push_subscriptions ON push_subscriptions;
